% Get root directory with all of the anipose and ephys data
disp('Choose the root directory with all of the anipose and ephys data')
root_dir = uigetdir('.', 'Choose root directory with all of the anipose and ephys data');

% Get save directory
disp('Choose common location to save trials')
save_dir = uigetdir('.', 'Choose common location to save trials');

reply = input(['\nDo you wish filter anipose data??\n\n',...
            '[Enter/y/Y]    => Yes\n',...
            '[n/N]          => No    \n'],'s');
switch lower(reply)
    case 'y'
        filter_anipose_flag = true;
    case 'n'
        filter_anipose_flag = false;
    otherwise
        filter_anipose_flag = true;
end
if filter_anipose_flag
    % Default score threhold
    scoreThresh = 0.05;
    reply = input(['\nWhat is filter score threshold??? ',...
                   sprintf('[Click Enter to use default = (%.2f)]\n', scoreThresh)],...
                    's');
    if ~isempty(reply)
        scoreThresh = str2num(reply);
    end
end
fillmissing_gapsize = 50;
% Get list of all dir with anipose data
disp('Extracting video locations')
indicator = 'pose-3d';
anipose_dir_list = listAniposeDir(root_dir, indicator);
disp(sprintf('Located %d locations', length(anipose_dir_list)))

for i = 1:length(anipose_dir_list)
   disp(sprintf('Initiating processing %s', anipose_dir_list{i}))
   % Get anipose and ephys data location
   anipose_ephys_loc = extractAniposeEphysDir(anipose_dir_list{i});
   % Load anipose data
   aniposeData = importAnipose3dData(anipose_ephys_loc.anipose_dir);
   if filter_anipose_flag
        [aniposeData] = filterAniposeDataTable(aniposeData, scoreThresh);
        aniposeData = fillmissing(aniposeData,...
                                  'linear',...
                                  'EndValues','nearest',...
                                  'MaxGap', fillmissing_gapsize);
   end
   % Load ephys data
   [EMG_trap,...
    EMG_biceps,...
    EMG_triceps,...
    EMG_ecu,...
    frameTrig,...
    laserTrig,...
    tone_on,...
    tone_off,...
    solenoid_on,...
    solenoid_off,...
    perchContact_on,...
    perchContact_off,...
    spoutContact_on,...
    spoutContact_off,...
    videoFrames_timestamps,...
    videoFrames_timeInSeconds,...
    aniposeData] = loadOEbinary_AT(anipose_ephys_loc.ephys_loc, aniposeData);
   % Segment data by trial
   trial_list = trial_segmentation(aniposeData,...
                                   solenoid_on,...
                                   spoutContact_on,...
                                   videoFrames_timestamps,...
                                   laserTrig,...
                                   EMG_biceps,...
                                   EMG_triceps,...
                                   EMG_ecu,...
                                   EMG_trap);
   disp(sprintf('Saving trials for %s', anipose_ephys_loc.label))
   save(fullfile(save_dir, strcat(anipose_ephys_loc.label, '.mat')), 'trial_list');
end