
function trial_list = trial_segmentation(aniposeData,...
										   startTrialTrigger,...
										   spoutContact_on,...
										   perchContact_on, perchContact_off,...
										   videoFrames_timestamps,...
										   laserTrig,...
										   EMG_biceps,...
										   EMG_triceps,...
										   EMG_ecu,...
										   EMG_trap,...
										   aniposeNumTS,...
										   ephysNumTS,...
										   contDataTimestamps,...
										   filterEMG)
% trial_list = trial_segmentation(aniposeData,...
% 										   startTrialTrigger,...
% 										   spoutContact_on,...
% 										   perchContact_on, perchContact_off,...
% 										   videoFrames_timestamps,...
% 										   laserTrig,...
% 										   EMG_biceps,...
% 										   EMG_triceps,...
% 										   EMG_ecu,...
% 										   EMG_trap,...
% 										   aniposeNumTS,...
% 										   ephysNumTS,...
% 										   contDataTimestamps);
%Output:
% ----------------
% 	trial_list: struct array with fields:
%			For (1) first spout contact (_first)
%				(2) last spout contact  (_last)
%				(3) fixed time interval (_fixed)
%                                AniposeData.allcolums, 
%                                EMG_biceps
%                                EMG_triceps
%                                EMG_ecu
%                                EMG_trap
%                                start_ts
%                                end_ts
%                                start_idx
%                                end_idx
% Inputs:
% aniposeData
% startTrialTrigger
% spoutContact_on
% perchContact_on, perchContact_off
% videoFrames_timestamps
% laserTrig
% EMG_biceps
% EMG_triceps
% EMG_ecu
% EMG_trap
% aniposeNumTS
% ephysNumTS
% contDataTimestamps

%trial segementation, segments trials from anipose data based on solenoid and spout contact, sorts trials into %lightON and lightOFF
%Anipose data segmented is a matrix,  each trial is a matrix  of openEphys index number X marker/error/EMG data
%each trial is the data(open Ephys and Anipose) between, Openephys index solenoidON and SpoutcontactON,
%if laser trigger within each trial is not equal to 0, sort into laserON,
%	condition: LightOFF/LightON, LightON and LightOFF trials (HEADER), each  N x 2  where N is the number %of trials,
%1> determine real trials, all values between solenoid ON indx and first spout contactON idx % mice make multiple %contacts in one trial we want to ignore those or use them later?
%2> eliminate trials before first video frame index % no video is recorded at this time
%concatenate videoFrames_timestamps vercat to Aniposedata 
%This code identifies the index positions corresponding to the the start and end of each, a trial starts with a solenoid_on and ends with the first spout contact,  it runs several checks to avoid multiple spout contacts and to account for trials where reward is presented but a reach does not happen, if this occurs within the recording or on the last trial

% Get First and all spout contact immediately after each start event (solenoid_on) and before next start event
perchContact_cont = convert_to_continuous(perchContact_on, perchContact_off, contDataTimestamps);
[spoutContact_first, spoutContact_multi, hitormiss, perchOnStart] = getSpoutContact(startTrialTrigger, spoutContact_on, perchContact_cont);

% Get contData.Timestamp reference for start and end of trial; As well as index into contData.Timestamp and anipose
%	- start_ts: contData.Timestamp value of start of trial
%	- start_idx: Index into contData.Timestamp; Also, index into aniposeData (row number)
%	- end_ts_first/ end_ts_last: contData.Timestamp value of first and last spout contact of trial (end of trial)
%	- end_ts_idx/ end_ts_idx: Index into contData.Timestamp and aniposeData for first and last spout contact of trial
[start_ts, start_idx,...
 end_ts_first, end_idx_first,...
 end_ts_last, end_idx_last] = getTrialEventInfo(startTrialTrigger, videoFrames_timestamps, hitormiss,...
  												spoutContact_first, spoutContact_multi);

% laserTrig is wrt contData.Timestamps
lightOnTrig_ts=contDataTimestamps(find(laserTrig>3.3));

for i = 1:length(startTrialTrigger)
	trial = getTrialInfo(aniposeData,...
						  EMG_biceps,...
						  EMG_triceps,...
						  EMG_ecu,...
						  EMG_trap,...
						  aniposeNumTS, ephysNumTS,...
						  contDataTimestamps,...
						  lightOnTrig_ts,...
						  hitormiss(i),...
						  perchOnStart(i),...
						  start_ts(i), start_idx(i),...
						  end_ts_first(i), end_idx_first(i),...
						  end_ts_last(i), end_idx_last(i),
						  filterEMG);
	fn = fieldnames(trial);
	for f =1:length(fn)
		trial_list(i).(fn{f}) = trial.(fn{f});
	end
end
